- name: install grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: start + ebanle grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: config grafana
  grafana_datasource:
    grafana_url: "http://localhost:3000"
    validate_certs: no
    name: "Prometheus"
    type: "prometheus"
    url: "http://localhost:9090"
    access: "proxy"
    is_default: yes
    login_user: "admin"
    login_password: "admin"

- name: add loki to grafana
  grafana_datasource:
    grafana_url: "http://localhost:3000"
    name: "Loki"
    type: "loki"
    url: "http://localhost:3100"
    access: "proxy"
    is_default: no
    login_user: "admin"
    login_password: "admin"
